### ISSUE TITLE
Update platform and sdk

### ISSUE THREAD

**Issue by trprado** [flathub/com.thincast.client#1]
When I run the `flatpak update` command, a menssage is displayed in the terminal and shows this:

```Info: org.kde.Platform//5.15 está em fim de vida, com motivo:
   We strongly recommend moving to the latest stable version of the Plaform and SDK
Applications that use this runtime:
   com.thincast.client
```

**Comment by mfleisz** [comment]
@trprado thanks for the report - we are aware of the issue and are working on releasing an updated version soon. Thanks for your patience - I'll post as soon as we are done!

**Comment by mfleisz** [comment]
@trprado this has been fixed now - please update the client to the latest version (1.0.348).
