### ISSUE TITLE
Thincast doesn't start anymore

### ISSUE THREAD

**Issue by wolfgang-58** [flathub/com.thincast.client#5]
Good morning,
Today there was an update of "Thincast", now the program doesn't start anymore, the error message is:
```
flatpak run com.thincast.client
rdc: error while loading shared libraries: libswscale.so.5: cannot open shared object file: No such file or directory
```
My System:
```
System:
  Kernel: 5.15.0-76-generic x86_64 bits: 64 Desktop: Cinnamon 5.6.8
    Distro: Linux Mint 21.1 Vera
Machine:
  Type: Laptop System: LENOVO product: 2429C93 v: ThinkPad T530
    serial: <superuser required>
  Mobo: LENOVO model: 2429C93 serial: <superuser required>
    UEFI-[Legacy]: LENOVO v: G4ETB7WW (2.77 ) date: 09/09/2019
Battery:
  ID-1: BAT0 charge: 10.9 Wh (100.0%) condition: 10.9/47.5 Wh (23.0%)
CPU:
  Info: dual core model: Intel Core i5-3320M bits: 64 type: MT MCP cache:
    L2: 512 KiB
  Speed (MHz): avg: 1196 min/max: 1200/3300 cores: 1: 1197 2: 1196 3: 1197
    4: 1197
Graphics:
  Device-1: Intel 3rd Gen Core processor Graphics driver: i915 v: kernel
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: modesetting
    unloaded: fbdev,vesa gpu: i915 resolution: 1366x768~60Hz
  OpenGL: renderer: Mesa Intel HD Graphics 4000 (IVB GT2)
    v: 4.2 Mesa 22.2.5-0ubuntu0.1~22.04.3
```
Thincast Version: 1.0.348

Thank you for your help
Wolfgang

**Comment by akallabeth** [comment]
@wolfgang-58 try a `flatpak update`, we had a glitch with a broken update, but that should already be fixed.

**Comment by akallabeth** [comment]
@wolfgang-58 ok, spoke too soon, still hanging in the build queue, sorry for the inconvenience.

**Comment by wolfgang-58** [comment]
@akallabeth: Unfortunately that doesn't work for me. I now have the commit=93c8e6a7a2190b549745e09d0ec08ad1e7c02751b013844115481d19f526f0e1
installed. 
This works...

**Comment by akallabeth** [comment]
@wolfgang-58 did update the latest version, the file hashes were wrong, with 9a14f6682e9238a2cc442b8e2dfae71751349b9b that should work.

**Comment by akallabeth** [comment]
@wolfgang-58 ok, latest build with https://github.com/flathub/com.thincast.client/commit/9a14f6682e9238a2cc442b8e2dfae71751349b9b is published and starts fine.
